paypal:
  client-id: AVha2Va2LzfaAiK6Xeleryi1EQjbTV_lJjh2_3Y_wRZvly4j_rxm_WusownGcxJ17_LTUGP36zAG8c5u
  client-secret: ECma-w7Whcv1qv0R2cP5xYEjYreSC9-Riwxx-Ygxr4Yw9q-JykIBt7zMW6R_PJG6YnYMyfxwa7jjx6WK
  mode: sandbox
